name: sync
on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: node build.js
      - name: Checkin
        run: |
          git config --global user.name 'uberushaximus'
          git config --global user.email 'uberushaximus@gmail.com'
          git add .
          git commit -a -m 'Automated Update' || echo "Blacklist Already Up-to-date"
          git push
